"""baseline: all phase 0 tables

Revision ID: 937afcc6a9b5
Revises: 
Create Date: 2026-02-15 08:59:04.263233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937afcc6a9b5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('household_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('family_name', sa.String(length=200), nullable=False),
    sa.Column('members', sa.Text(), nullable=False),
    sa.Column('cook_info', sa.Text(), nullable=False),
    sa.Column('rules', sa.Text(), nullable=False),
    sa.Column('kid_general_rules', sa.Text(), nullable=False),
    sa.Column('pantry_staples', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leftovers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dish_name', sa.String(length=200), nullable=False),
    sa.Column('recipe_id', sa.String(length=100), nullable=True),
    sa.Column('servings_estimate', sa.String(length=30), nullable=False),
    sa.Column('date_logged', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('leftovers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_leftovers_date_logged'), ['date_logged'], unique=False)

    op.create_table('meal_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('history_date', sa.Date(), nullable=False),
    sa.Column('meal_plan_id', sa.Integer(), nullable=True),
    sa.Column('dishes_cooked', sa.Text(), nullable=False),
    sa.Column('egg_style', sa.Text(), nullable=False),
    sa.Column('cuisine', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_history_history_date'), ['history_date'], unique=True)

    op.create_table('meal_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('cuisine', sa.String(length=50), nullable=False),
    sa.Column('dishes', sa.Text(), nullable=False),
    sa.Column('egg_style', sa.String(length=20), nullable=False),
    sa.Column('include_curd_rice_side', sa.Boolean(), nullable=False),
    sa.Column('roti_count', sa.String(length=100), nullable=False),
    sa.Column('kid_notes', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('cook_brief_text', sa.Text(), nullable=False),
    sa.Column('voice_script_text', sa.Text(), nullable=False),
    sa.Column('voice_audio_url', sa.String(length=500), nullable=True),
    sa.Column('shopping_list', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_plans_plan_date'), ['plan_date'], unique=False)

    op.create_table('meal_templates',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_components', sa.Text(), nullable=False),
    sa.Column('optional_components', sa.Text(), nullable=False),
    sa.Column('carb_rules', sa.Text(), nullable=False),
    sa.Column('roti_rules', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cuisine_tags', sa.Text(), nullable=False),
    sa.Column('meal_template', sa.String(length=50), nullable=False),
    sa.Column('is_side_dish', sa.Boolean(), nullable=False),
    sa.Column('ingredients', sa.Text(), nullable=False),
    sa.Column('steps', sa.Text(), nullable=False),
    sa.Column('critical_notes', sa.Text(), nullable=False),
    sa.Column('kid_adaptation', sa.Text(), nullable=False),
    sa.Column('preferred_side_pairings', sa.Text(), nullable=False),
    sa.Column('protein_tier', sa.String(length=20), nullable=False),
    sa.Column('cook_familiarity', sa.String(length=30), nullable=False),
    sa.Column('links', sa.Text(), nullable=False),
    sa.Column('recipe_audio_url', sa.String(length=500), nullable=True),
    sa.Column('serves', sa.String(length=20), nullable=False),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=True),
    sa.Column('cook_time_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_lists',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('list_date', sa.Date(), nullable=False),
    sa.Column('meal_plan_id', sa.Integer(), nullable=True),
    sa.Column('items', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shopping_lists_list_date'), ['list_date'], unique=False)

    op.create_table('veg_availability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('vegetables', sa.Text(), nullable=False),
    sa.Column('use_soon', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('veg_availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_veg_availability_snapshot_date'), ['snapshot_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veg_availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veg_availability_snapshot_date'))

    op.drop_table('veg_availability')
    with op.batch_alter_table('shopping_lists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shopping_lists_list_date'))

    op.drop_table('shopping_lists')
    op.drop_table('recipes')
    op.drop_table('meal_templates')
    with op.batch_alter_table('meal_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_plans_plan_date'))

    op.drop_table('meal_plans')
    with op.batch_alter_table('meal_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_history_history_date'))

    op.drop_table('meal_history')
    with op.batch_alter_table('leftovers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_leftovers_date_logged'))

    op.drop_table('leftovers')
    op.drop_table('household_profiles')
    # ### end Alembic commands ###
