"""Schemas for meal plan generation, approval, and display."""

from datetime import date, datetime
from typing import Literal

from pydantic import BaseModel, Field


EggStyle = Literal["boiled", "omelette", "scrambled", "fried"]
PlanStatus = Literal["draft", "approved", "completed"]


class DishEntry(BaseModel):
    """A dish within a meal plan."""
    recipe_id: str
    role: str  # main, main_curry, curry, side, side_dish, accompaniment, salad
    name: str


class MealPlanCandidate(BaseModel):
    """A candidate meal plan generated by AI."""
    template_id: str
    cuisine: str
    dishes: list[DishEntry] = Field(default_factory=list)
    egg_style: EggStyle = "boiled"
    include_curd_rice_side: bool = False
    roti_count: str = "standard batch"
    kid_notes: str = ""
    rationale: str = ""
    missing_ingredients: list[str] = Field(default_factory=list)


class GeneratePlansRequest(BaseModel):
    """Request to generate meal plans from check-in data."""
    plan_date: date
    vegetables: list[str] = Field(default_factory=list)
    use_soon: list[str] = Field(default_factory=list)
    leftovers: list[dict] = Field(default_factory=list)


class ValidationInfo(BaseModel):
    """Validation result from the rules engine."""
    is_valid: bool = True
    violations: list[str] = Field(default_factory=list)


class MealPlanResponse(BaseModel):
    """Response for a single meal plan."""
    id: int
    plan_date: date
    status: str
    template_id: str
    cuisine: str
    dishes: list[DishEntry] = Field(default_factory=list)
    egg_style: str
    include_curd_rice_side: bool = False
    roti_count: str = ""
    kid_notes: str = ""
    rationale: str = ""
    cook_brief_text: str = ""
    voice_script_text: str = ""
    voice_audio_url: str | None = None
    shopping_list: list[dict] = Field(default_factory=list)
    validation: ValidationInfo | None = None
    created_at: datetime
    approved_at: datetime | None = None

    model_config = {"from_attributes": True}


class MealPlanApproveResponse(BaseModel):
    """Response after approving a meal plan."""
    plan: MealPlanResponse
    history_recorded: bool = False


class SwapDishRequest(BaseModel):
    """Request to swap a dish in a plan."""
    plan_id: int
    old_recipe_id: str
    new_recipe_id: str
    new_recipe_name: str
    new_role: str = "main"


class SwapOptionItem(BaseModel):
    """A recipe available as a swap alternative."""
    id: str
    name: str
    cuisine_tags: list[str] = Field(default_factory=list)
    meal_template: str = ""
    is_side_dish: bool = False
    protein_tier: str = "medium"
    cook_familiarity: str = "needs_instructions"


class CurdRiceToggleRequest(BaseModel):
    """Request to toggle the optional curd rice side."""
    include: bool


class MealHistoryResponse(BaseModel):
    """Response for a meal history entry."""
    id: int
    history_date: date
    meal_plan_id: int | None = None
    dishes_cooked: list[str] = Field(default_factory=list)
    egg_style: str = ""
    cuisine: str = ""
    notes: str = ""
    created_at: datetime

    model_config = {"from_attributes": True}
